/*
 * Projet L3 STRI 
 * Device Manager
 *
 */
package VueJtree;

import BaseDeDonnees.ConnexionBDD;
import Metier.*;

import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 * Cette classe définit une interface graphique pour l'ajout d'une salle. Elle
 * montre la façon de procéder lors de l'ajout d'un objet qui pourrait, avec
 * plus de temps, aboutir à l'ajout des autres objets.
 *
 * @author Manavai
 */
public class AddSalle extends javax.swing.JPanel {

    /**
     *
     * Creates new form AddObj
     *
     * @param arbreModele Modèle Jtree a passer
     * @param node_batiment Node de batiment
     */
    public AddSalle(DefaultTreeModel arbreModele, DefaultMutableTreeNode node_batiment) {

        this.on_bat = node_batiment;
        this.arbreModele = arbreModele;

        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        numero = new javax.swing.JTextField();
        etage = new javax.swing.JTextField();
        addSalleConfirm = new javax.swing.JButton();
        addSalleCancel = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Nom:");

        jLabel2.setText("Numéro de Salle");

        jLabel3.setText("Etage");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setText("Création d'une nouvelle salle");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Manavai\\workspace\\Projet-Java-L3-STRI\\src\\main\\java\\VueJtree\\salles.png")); // NOI18N

        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        addSalleConfirm.setBackground(new java.awt.Color(102, 255, 255));
        addSalleConfirm.setText("Ajouter");
        addSalleConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalleConfirmActionPerformed(evt);
            }
        });

        addSalleCancel.setBackground(new java.awt.Color(255, 51, 51));
        addSalleCancel.setText("Annuler");
        addSalleCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSalleCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(etage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addComponent(numero, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel5))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSalleConfirm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSalleCancel)
                .addGap(9, 9, 9))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(etage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addSalleConfirm)
                    .addComponent(addSalleCancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void addSalleConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalleConfirmActionPerformed
        // TODO add your handling code here:
        int i = Integer.parseInt(etage.getText()); // conversion string en entier

        new_salle = new Salle(nom.getText(), numero.getText(), i); //salle temporaire

        // mise en BD
        try {

            // on essaye de se connecter à la BD
            ConnexionBDD db = new ConnexionBDD("jdbc:mysql://binary-digit.net:3306/java", "java", "java");

            //insertion dans la base de donnée
            int temp_id = db.insertSalleIntoBatiment(new_salle, on_bat.toString());
            new_salle.setId(temp_id);

            // fermeture de la connexion
            db.closeConnexionBDD();

        } catch (ClassNotFoundException | SQLException ex) {
            System.out.println("La nouvelle salle n'a pa pû être ajoutée dans la BdD");
        }

        DefaultMutableTreeNode Jtree_Salle = new DefaultMutableTreeNode();// on créer un sous-node sur le JTree
        Jtree_Salle.setUserObject(new_salle); // attribution objet salle à une node

        on_bat.add(Jtree_Salle); // ajout node salle au node batiment
        // rechargement arbo
        arbreModele.reload(on_bat);

        // fermture ...
        JDialog dial = (JDialog) this.getParent().getParent().getParent().getParent(); // on récupère le gros container et on le ferme.
        dial.dispose(); // fermeture

        // ainsi l'évenement oncloseWindow s'occupera de récupérer les valeurs entrées.
    }//GEN-LAST:event_addSalleConfirmActionPerformed

    private void addSalleCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSalleCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);

        // on récupère le Jdialog pour le fermer
        JDialog dial = (JDialog) this.getParent().getParent().getParent().getParent(); // on récupère le gros container et on le ferme.
        dial.dispose(); // fermeture


    }//GEN-LAST:event_addSalleCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addSalleCancel;
    private javax.swing.JButton addSalleConfirm;
    public javax.swing.JTextField etage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JTextField nom;
    public javax.swing.JTextField numero;
    // End of variables declaration//GEN-END:variables

    // pour l'ajout d'une salle;
    public Salle new_salle;
    public DefaultMutableTreeNode on_bat;
    public DefaultTreeModel arbreModele;

}
